Data preprocessing page
AlexandreSajus/TalkToTaipy pull request #62
Opened 2023-08-30 06:41 UTC by thanhnew2001

- Allow to change data type and title
- Data type is still in text as no combo box in TaipyGUI
- Re-generate suggested prompts when column title changes

2023-08-30 11:58 UTC, AlexandreSajus commented on utils.py
> +def generate_completion(prompt):
Why is this function needed?

2023-08-30 11:58 UTC, AlexandreSajus commented on utils.py
> -def generate_prompts(string_columns, float_columns, date_columns, int_columns):
Why was my approach to generating prompts scrapped (the one in my last PR)?

2023-08-30 12:02 UTC, AlexandreSajus requested changes
Good iteration! The new page is almost what we need.

Some things we will need to fix (I will keep this PR open so we can work on it):
- Types should be chosen from a dropdown menu instead of a text input
- When a conversion to a type fails, we should give the choice to the user to cancel or remove rows that are problematic
- We probably need a UI / Layout pass
- Why were my changes to prompt generation scrapped in this PR?

2023-08-30 13:18 UTC, thanhnew2001 commented on utils.py
> -def generate_prompts(string_columns, float_columns, date_columns, int_columns):
I moved this into util.py

2023-08-30 13:19 UTC, thanhnew2001 commented on utils.py
> +def generate_completion(prompt):
This can be removed. Initially, I planned to use openAI to suggest good prompts but they request a paid account

2023-08-30 13:22 UTC, thanhnew2001 commented
Types should be chosen from a dropdown menu instead of a text input 
--> Currently, TaipyGUI does not support it. Haven't found a better way
When a conversion to a type fails, we should give the choice to the user to cancel or remove rows that are problematic
--> Sure, will take some time to rework that way
We probably need a UI / Layout pass
--> Yes, definitely, TaipyGUI has some limits but we can find a workaround
Why were my changes to prompt generation scrapped in this PR?
--> Sorry, I moved some functions around. Let me know if anything is really missing.

2023-09-01 12:05 UTC, AlexandreSajus commented
Two missing items left:
- Skip problematic rows when type conversion fails, ask/notify the user
- UX pass using an editable table:

We should replace this layout:
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/62465003/9e37fcf5-6eba-4bd8-990e-dc28ac74ec36)

With an editable table that contains two rows: columns names and column type
on_edit we will change the column names and types

2023-09-04 11:02 UTC, AlexandreSajus commented
Changing column names and types is now done through an editable table, making the UX more appealing.

Two missing items:
- If a type conversion fails, the user should be given the choice to ignore rows where the conversion fails
- Some buttons (Reset App, Reset Columns) need fixing since we have added new variables to the app

2023-09-06 19:30 UTC, AlexandreSajus commented
The branch should be stable now. Fixed the following issues:
- :wrench: Reset data before a new prompt execution to avoid prompting on a dataset missing columns
- :wrench: Rewrote the initial prompt suggestions
- :bug: Reset Data button should not reset the data preprocessing
- :bug: Reset App fails
- :bug: Reset App after uploading a dataset shows 10 prompt suggestions
- :wrench: Switch type names to lowercase
- :bug: Prompt builder should reset after editing column names or types
- :bug: Prompt suggestions should reset after editing column names or types
- :memo: Add a message to ask the user to refresh the page if generating a graph fails

2023-09-06 19:31 UTC, AlexandreSajus approved these changes

2023-09-06 19:34 UTC, AlexandreSajus commented
Fixes #55 
Fixes #60 
Fixes #63

2023-09-07 11:05 UTC, merged